---
params: 
  dirSummaryRes: "`r list()`"
title: "QC Summary"
subtitle: "`r params$dirSummaryRes$project`"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M %Z')`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r warning=FALSE, include=FALSE}

setwd(params$dirSummaryRes$wd)

dir_summary_data <- params$dirSummaryRes$data

qc_status <- params$dirSummaryRes$status

logSum <- 
  review::logSummary() %>% 
  dplyr::transmute(
    File = file,
    `Last...QCed...rev` = revf
  )

```

\newpage

# Summaries

\newpage

## QC Pending

```{r message=FALSE, results='asis'}

needs_qc <-
  dir_summary_data %>% 
  dplyr::filter(Status == "In QC log, needs QC") %>% 
  dplyr::left_join(logSum) %>% 
  dplyr::arrange(Author) %>% 
  dplyr::rename(`Last...rev` = `Latest rev`) %>% 
  dplyr::select(Author, File, QCer, `Last...rev`, `Last...QCed...rev`) %>% 
  suppressMessages()

if (nrow(needs_qc) == 0) {
  needs_qc <- dplyr::tibble(Author = "None", File = "None")
}

needs_qc %>%   
  pmtables::st_new() %>% 
  pmtables::st_clear_reps("Author") %>%
  pmtables::st_bold(cols = "Author") %>% 
  pmtables::st_center(File = pmtables::col_ragged(8)) %>% 
  pmtables::stable_long() %>%
  pmtables::st_asis()

```

\newpage

## Latest modified scripts not in QC log

```{r message=FALSE, results='asis'}

not_in_log <-
  dir_summary_data %>%
  dplyr::filter(grepl("script/", File, fixed = TRUE)) %>% 
  dplyr::filter(Status == "Not in QC log") %>% 
  dplyr::rename(`Latest...rev` = `Latest rev`) %>% 
  dplyr::mutate(
    `Latest edit` = as.Date(`Latest edit`),
    `Days since...last edit` = as.numeric(Sys.Date() - `Latest edit`)) %>% 
  dplyr::select(File, Author, `Days since...last edit`, `Latest...rev`) %>% 
  dplyr::arrange(`Days since...last edit`) %>% 
  dplyr::slice(1:30)

if (nrow(not_in_log) == 0) {
  not_in_log <- dplyr::tibble(Author = "None", File = "None")
}

not_in_log %>%   
  pmtables::st_new() %>% 
  pmtables::st_center(File = pmtables::col_ragged(8)) %>% 
  pmtables::stable_long() %>%
  pmtables::st_asis()

```

\newpage

# Contributors

\newpage

```{r, results='asis'}
authors <- 
  dir_summary_data %>%
  dplyr::filter(Directory != ".") %>%
  dplyr::distinct(Author) %>%
  dplyr::pull(Author)

for (author.i in authors) {
  
  writeLines(paste0("## ", author.i))
  
  directories.i <-
    dir_summary_data %>% 
    dplyr::filter(Directory != ".") %>%
    dplyr::filter(Author == author.i) %>% 
    dplyr::distinct(Directory) %>%
    dplyr::pull(Directory)
  
  if (length(directories.i) == 0) {
    next
  }
  
  for (directory.i in directories.i) {
    
    writeLines(paste0("### ", directory.i))
    
    tab.i <-
      dir_summary_data %>%
      dplyr::filter(Author == author.i) %>%
      dplyr::filter(Directory == directory.i) %>%
      dplyr::mutate(`Latest edit` = as.Date(`Latest edit`)) %>% 
      dplyr::rename(`Latest...rev` = `Latest rev`, `Latest...edit` = `Latest edit`) %>% 
      dplyr::select(File, `Latest...edit`, Status, `Latest...rev`, QCer) %>%
      dplyr::arrange(Status) %>%
      pmtables::st_new() %>%
      pmtables::st_panel("Status") %>%
      pmtables::st_center(File = pmtables::col_ragged(8)) %>% 
      pmtables::stable_long()
    
    pmtables::st_wrap(tab.i)
    
    rm(tab.i)
    
    writeLines("\n")
    writeLines("\\newpage")
  }
  
}

```
