---
title: "QC Log Summary"
author: "`r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
params: 
  dirSum: "`r list()`"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(pmtables)
library(review)
```

```{r, include=FALSE}
dir_summary <- params$dirSum
dir_summary$data <-
  dir_summary$data %>%
  arrange(Author) %>% 
  filter(Status != "Not in SVN") %>%
  mutate(Status = factor(Status, levels = c("Not in QC log", "In QC log, needs QC", "QC up to date")))
```

\newpage

# Summaries

\newpage

## Needs QC

```{r, results='asis'}

dir_summary$data %>% 
  dplyr::filter(Status == "In QC log, needs QC") %>% 
  dplyr::count(Author) %>% 
  dplyr::rename(`Scripts needing QC` = n) %>%
  stable() %>%
  st_asis()
  
```

\newpage

# Authors

\newpage

```{r, results='asis'}
authors <- dir_summary$data %>% distinct(Author) %>% pull(Author)
for (author.i in authors) {
  writeLines(paste0("## ", author.i))
  tab.i <-
    dir_summary$data %>%
    filter(Author == author.i) %>%
    select(File, `Latest edit`, QCer, Status) %>%
    arrange(Status) %>%
    st_new() %>%
    st_panel("Status") %>%
    stable_long(
      lt_cap_text = paste0("Project ", dir_summary$project, "- QC checker for all scripts in ", basename(dir_summary$directory), " for ", author.i)
    )
  st_wrap(tab.i)
  
  writeLines("\n")
  writeLines("\\newpage")
}
```